name: scan

on:
  schedule:
    # Scan the image regularly (once a day)
    - cron: '45 03 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Scan current image & report results
    runs-on: "ubuntu-24.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: "ghcr.io/TLNBS2405/heihachi"
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          vuln-type: "os"
          timeout: '15m0s'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
